"""26.08 -- One-time preprocessing for "Opcja A" (semi-weak supervision, see plans and summaries/
6.08_PODSUMOWANIE_PROCESU.md Etap 32 and the approved plan this implements): turns the 42 raw,
uncropped ZEGAR photos into production-format single-otolith crops the main training pipeline
(src/dataset.py::OtolithDataset) can load directly, plus a small side-table of real ring (x, y)
positions in each crop's own pixel space.

Deliberately produces files SEPARATE from the main data/labels_combined.csv + Z:/Photo/.../Processed
(see cfg.data.zegar_extra_labels_csv/zegar_extra_image_dir/zegar_targets_csv, src/config.py) rather
than writing into them directly -- the main labels CSV is regenerated by scripts/prepare_labels.py on
every RESCAN=True training run (scan of the real Excel + image directory), which would silently drop
any ZEGAR rows written there, disabling zegar_position_weight without any error. Keeping ZEGAR data
in its own files makes it immune to that.

Design decisions (see the approved plan / Etap 32 for full reasoning, not repeated here):
  - NO axis-canonicalization rotation (unlike the earlier from-scratch Option-B experiment) --
    RadialAttentionDensityHead already receives per-image (t, theta) positional encoding computed
    independently by compute_polar_grid, so a physical pixel rotation is unnecessary and would only
    risk new border artifacts.
  - NO background masking at preprocessing time -- OtolithDataset already masks on the fly
    (mask_background=true) for every image, ZEGAR or not; pre-masking would double up / diverge from
    how production images are treated.
  - 42 samples split ~30 "train" (get position supervision) / ~12 "held-out" (excluded from BOTH
    output CSVs entirely -- never enter training in any role) for an honest, non-circular post-hoc
    evaluation via scripts/diagnostics/expert_annotation_eval.py afterward.
  - Both readers' (KK + SS) points used as independent Gaussian centers, UNMATCHED -- same precedent
    already validated in scripts/diagnostics/train_zegar_localization_head.py::build_dataset (their
    heavily-overlapping Gaussians merge into one blob per ring under the "max of Gaussians"
    convention anyway, since sigma=1.2 patches >> the ~4px KK/SS disagreement).

Usage:
    python scripts/prepare_zegar_semi_weak_data.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
DIAG_DIR = PROJECT_ROOT / "scripts" / "diagnostics"
if str(DIAG_DIR) not in sys.path:
    sys.path.insert(0, str(DIAG_DIR))

import numpy as np
import pandas as pd
from PIL import Image as PILImage

import expert_annotation_eval as ev
from scripts.run_pipeline import load_merged_config

# ============================================================
# KONFIGURACJA -- zmień tylko tutaj
# ============================================================

# Segmentation params source -- Run N's config (the config this feature is designed to be layered
# onto, config_zegar_semi_weak.yaml is a copy of it) so the crop geometry matches exactly what
# training will use.
REFERENCE_CONFIG = PROJECT_ROOT / "configs" / "config_radial_attention.yaml"

OUT_IMAGE_DIR = PROJECT_ROOT / "data" / "ZEGAR" / "Processed"
OUT_LABELS_CSV = PROJECT_ROOT / "data" / "zegar_semi_weak_labels.csv"
OUT_TARGETS_CSV = PROJECT_ROOT / "data" / "zegar_semi_weak_targets.csv"
OUT_SPLIT_JSON = PROJECT_ROOT / "data" / "zegar_semi_weak_split.json"

SEED = 42                 # matches this project's standing seed convention
HELDOUT_FRACTION = 0.28   # ~12/42 -- see module docstring for why these are excluded entirely

# ============================================================


def build_crops(ann: pd.DataFrame, seg_params: dict) -> dict:
    """Crop every sample once (no masking, no rotation -- see module docstring), save to
    OUT_IMAGE_DIR, and return {sample: {"age": int, "points": [(x, y), ...]}} in the SAVED crop's
    own pixel space. Samples where cropping fails are silently excluded (same graceful-degradation
    philosophy as every other ZEGAR diagnostic script)."""
    OUT_IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    samples = sorted(ann["Sample"].unique())
    data: dict = {}
    n_failed = 0
    for i, sample in enumerate(samples, 1):
        raw_image_id = f"{sample}.jpg"   # to read the RAW, uncropped ZEGAR photo
        sub = ann[ann.Sample == sample]
        mean_xy = (float(sub.x.mean()), float(sub.y.mean()))
        raw_rgb = np.array(PILImage.open(ev.IMAGE_DIR / raw_image_id).convert("RGB"), dtype=np.uint8)
        cropped, x0, y0, _used_second = ev.resolve_and_crop_target_otolith(raw_rgb, mean_xy, seg_params)
        if cropped is None:
            print(f"  [{i}/{len(samples)}] {sample}: crop failed, skipping")
            n_failed += 1
            continue

        ages = sub["age"].unique()
        if len(ages) > 1:
            print(f"  [{i}/{len(samples)}] {sample}: WARNING readers disagree on age {ages}, "
                  f"using {int(ages[0])}")
        age = int(ages[0])

        points = [(float(row.x - x0), float(row.y - y0)) for row in sub.itertuples()]

        # "ZEGAR_" prefix is NOT cosmetic: OtolithDataset's mask cache
        # (data/masks_cache/<stem>_mask.png) keys purely by filename stem, with no
        # awareness of directory or image shape. A processed crop saved as plain
        # "Z01.jpg" would collide with any mask ever cached under that same stem for
        # the RAW, differently-shaped ZEGAR photo (confirmed happening in practice:
        # a stale data/masks_cache/Z01_mask.png from an earlier, unrelated run is
        # 2880x2048 vs this crop's ~750x1600, causing a shape-mismatch crash the
        # first time OtolithDataset tried to mask this file). The prefix guarantees
        # the stem can never collide with the raw sample name.
        out_image_id = f"ZEGAR_{sample}.jpg"
        out_path = OUT_IMAGE_DIR / out_image_id
        PILImage.fromarray(cropped).save(out_path, quality=95)

        data[sample] = {"image_id": out_image_id, "age": age, "points": points}
        print(f"  [{i}/{len(samples)}] {sample}: OK ({len(points)} points, age={age}, "
              f"crop={cropped.shape[1]}x{cropped.shape[0]}) -> {out_image_id}")
    print(f"Built {len(data)}/{len(samples)} crops ({n_failed} failed)")
    return data


def make_split(samples: dict, seed: int, heldout_fraction: float) -> tuple[list[str], list[str]]:
    """Age-stratified random split -- held-out samples are EXCLUDED from training entirely (see
    module docstring), so this must be decided ONCE, deterministically, and saved for the later
    evaluation step to know which samples are honestly never-seen-in-training."""
    rng = np.random.RandomState(seed)
    by_age: dict[int, list[str]] = {}
    for sample, info in samples.items():
        by_age.setdefault(info["age"], []).append(sample)

    held_out: list[str] = []
    for age, group in by_age.items():
        group = sorted(group)
        rng.shuffle(group)
        n_hold = max(1, round(len(group) * heldout_fraction)) if len(group) >= 2 else 0
        held_out.extend(group[:n_hold])
    held_out = sorted(held_out)
    train = sorted(s for s in samples if s not in held_out)
    return train, held_out


def main() -> None:
    print("=" * 70)
    print("Przygotowanie danych ZEGAR dla semi-slabego nadzoru (Opcja A, 26.08)")
    print("=" * 70)

    print("\n[1/4] Wczytywanie adnotacji (bez core/edge/ostatniego przyrostu, 24.08 fix)...")
    ann = ev.load_expert_annotations()
    ev.validate_annotation_bounds(ann, ev.IMAGE_DIR)

    print("\n[2/4] Wczytanie parametrow segmentacji (z config_radial_attention.yaml)...")
    cfg = load_merged_config(REFERENCE_CONFIG, None)
    seg_params = cfg.segmentation.as_params()

    print("\n[3/4] Crop kazdej z 42 probek (bez maskowania, bez rotacji)...")
    samples = build_crops(ann, seg_params)

    print(f"\n[4/4] Podzial {SEED=}, held-out frakcja={HELDOUT_FRACTION}...")
    train_ids, heldout_ids = make_split(samples, SEED, HELDOUT_FRACTION)
    print(f"  train (dostaja nadzor pozycyjny): {len(train_ids)} -> {train_ids}")
    print(f"  held-out (calkowicie wykluczone z treningu): {len(heldout_ids)} -> {heldout_ids}")

    labels_rows = [
        {"image_id": samples[s]["image_id"], "age": samples[s]["age"], "split": "train"}
        for s in train_ids
    ]
    pd.DataFrame(labels_rows).to_csv(OUT_LABELS_CSV, index=False)

    target_rows = [
        {"image_id": samples[s]["image_id"], "x": x, "y": y}
        for s in train_ids
        for x, y in samples[s]["points"]
    ]
    pd.DataFrame(target_rows).to_csv(OUT_TARGETS_CSV, index=False)

    OUT_SPLIT_JSON.write_text(json.dumps({
        "seed": SEED, "heldout_fraction": HELDOUT_FRACTION,
        "train": train_ids, "held_out": heldout_ids,
    }, indent=2), encoding="utf-8")

    print(f"\nZapisano:")
    print(f"  {OUT_IMAGE_DIR} ({len(samples)} obrazow)")
    print(f"  {OUT_LABELS_CSV} ({len(labels_rows)} wierszy)")
    print(f"  {OUT_TARGETS_CSV} ({len(target_rows)} wierszy)")
    print(f"  {OUT_SPLIT_JSON}")
    print(f"\nNastepny krok: configs/config_zegar_semi_weak.yaml wskazuje na te pliki "
          f"(zegar_extra_labels_csv/zegar_extra_image_dir/zegar_targets_csv); "
          f"main_zegar_semi_weak.py na serwerze uruchamia pelny trening.")


if __name__ == "__main__":
    main()
